theme: jekyll-theme-slate
title: Welcome to the Reality Toolkit provided by the Reality Collective
description: The Reality Toolkit's primary focus is to make it extremely easy to get started creating Mixed Reality applications and to accelerate deployment to multiple platforms from the same Unity project.
