import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The Collective's own documentation (docs/): welcome, build server, project templates, automation.
// The Reality Toolkit WebXR documentation is a separate docs instance, see webxr-sidebars.ts.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
