import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar for the stack as a whole and one per family. Each family sidebar opens with a link to the
// family's overview page (a styled React page under src/pages/webxr/), then its Basics, Adapters and
// Examples categories, generated from the folder. Ordering comes from sidebar_position front matter
// and _category_.json files.
function family(dir: string, label: string) {
  return [
    {type: 'link' as const, label: `${label} overview`, href: `/webxr/${dir}`},
    {type: 'autogenerated' as const, dirName: dir},
  ];
}

const sidebars: SidebarsConfig = {
  stack: [
    'index',
    {type: 'autogenerated', dirName: 'concepts'},
    'walkthrough-first-iwsdk-scene',
    {type: 'link', label: 'Quick start: every framework on IWSDK', href: '/docs/get-started-webxr'},
    {
      type: 'category',
      label: 'The families',
      collapsed: false,
      items: [
        {type: 'link', label: 'Input', href: '/webxr/input'},
        {type: 'link', label: 'Interactions', href: '/webxr/interactions'},
        {type: 'link', label: 'UI Extensions', href: '/webxr/uiextensions'},
        {type: 'link', label: 'Environment', href: '/webxr/environment'},
      ],
    },
  ],
  input: family('input', 'Input'),
  interactions: family('interactions', 'Interactions'),
  uiextensions: family('uiextensions', 'UI Extensions'),
  environment: family('environment', 'Environment'),
};

export default sidebars;
